# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ahuang9999/fintech-intern-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ahuang9999/fintech-intern-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/ahuang9999/.cache/pypoetry/virtualenvs/intern-project-sOTACgVk-py3.12/lib64/python3.12/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ahuang9999/fintech-intern-project/CMakeFiles /home/ahuang9999/fintech-intern-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ahuang9999/fintech-intern-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intern_project

# Build rule for target.
intern_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intern_project
.PHONY : intern_project

# fast build rule for target.
intern_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_project.dir/build.make CMakeFiles/intern_project.dir/build
.PHONY : intern_project/fast

#=============================================================================
# Target rules for targets named intern_tests

# Build rule for target.
intern_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intern_tests
.PHONY : intern_tests

# fast build rule for target.
intern_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/build
.PHONY : intern_tests/fast

#=============================================================================
# Target rules for targets named intern

# Build rule for target.
intern: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intern
.PHONY : intern

# fast build rule for target.
intern/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern.dir/build.make CMakeFiles/intern.dir/build
.PHONY : intern/fast

src/cppsrc/main.o: src/cppsrc/main.cpp.o
.PHONY : src/cppsrc/main.o

# target to build an object file
src/cppsrc/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_project.dir/build.make CMakeFiles/intern_project.dir/src/cppsrc/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern.dir/build.make CMakeFiles/intern.dir/src/cppsrc/main.cpp.o
.PHONY : src/cppsrc/main.cpp.o

src/cppsrc/main.i: src/cppsrc/main.cpp.i
.PHONY : src/cppsrc/main.i

# target to preprocess a source file
src/cppsrc/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_project.dir/build.make CMakeFiles/intern_project.dir/src/cppsrc/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern.dir/build.make CMakeFiles/intern.dir/src/cppsrc/main.cpp.i
.PHONY : src/cppsrc/main.cpp.i

src/cppsrc/main.s: src/cppsrc/main.cpp.s
.PHONY : src/cppsrc/main.s

# target to generate assembly for a file
src/cppsrc/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_project.dir/build.make CMakeFiles/intern_project.dir/src/cppsrc/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern.dir/build.make CMakeFiles/intern.dir/src/cppsrc/main.cpp.s
.PHONY : src/cppsrc/main.cpp.s

src/cppsrc/test/test_basic.o: src/cppsrc/test/test_basic.cpp.o
.PHONY : src/cppsrc/test/test_basic.o

# target to build an object file
src/cppsrc/test/test_basic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_basic.cpp.o
.PHONY : src/cppsrc/test/test_basic.cpp.o

src/cppsrc/test/test_basic.i: src/cppsrc/test/test_basic.cpp.i
.PHONY : src/cppsrc/test/test_basic.i

# target to preprocess a source file
src/cppsrc/test/test_basic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_basic.cpp.i
.PHONY : src/cppsrc/test/test_basic.cpp.i

src/cppsrc/test/test_basic.s: src/cppsrc/test/test_basic.cpp.s
.PHONY : src/cppsrc/test/test_basic.s

# target to generate assembly for a file
src/cppsrc/test/test_basic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_basic.cpp.s
.PHONY : src/cppsrc/test/test_basic.cpp.s

src/cppsrc/test/test_feature_n_trades.o: src/cppsrc/test/test_feature_n_trades.cpp.o
.PHONY : src/cppsrc/test/test_feature_n_trades.o

# target to build an object file
src/cppsrc/test/test_feature_n_trades.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_n_trades.cpp.o
.PHONY : src/cppsrc/test/test_feature_n_trades.cpp.o

src/cppsrc/test/test_feature_n_trades.i: src/cppsrc/test/test_feature_n_trades.cpp.i
.PHONY : src/cppsrc/test/test_feature_n_trades.i

# target to preprocess a source file
src/cppsrc/test/test_feature_n_trades.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_n_trades.cpp.i
.PHONY : src/cppsrc/test/test_feature_n_trades.cpp.i

src/cppsrc/test/test_feature_n_trades.s: src/cppsrc/test/test_feature_n_trades.cpp.s
.PHONY : src/cppsrc/test/test_feature_n_trades.s

# target to generate assembly for a file
src/cppsrc/test/test_feature_n_trades.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_n_trades.cpp.s
.PHONY : src/cppsrc/test/test_feature_n_trades.cpp.s

src/cppsrc/test/test_feature_pct_buy_trades.o: src/cppsrc/test/test_feature_pct_buy_trades.cpp.o
.PHONY : src/cppsrc/test/test_feature_pct_buy_trades.o

# target to build an object file
src/cppsrc/test/test_feature_pct_buy_trades.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_pct_buy_trades.cpp.o
.PHONY : src/cppsrc/test/test_feature_pct_buy_trades.cpp.o

src/cppsrc/test/test_feature_pct_buy_trades.i: src/cppsrc/test/test_feature_pct_buy_trades.cpp.i
.PHONY : src/cppsrc/test/test_feature_pct_buy_trades.i

# target to preprocess a source file
src/cppsrc/test/test_feature_pct_buy_trades.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_pct_buy_trades.cpp.i
.PHONY : src/cppsrc/test/test_feature_pct_buy_trades.cpp.i

src/cppsrc/test/test_feature_pct_buy_trades.s: src/cppsrc/test/test_feature_pct_buy_trades.cpp.s
.PHONY : src/cppsrc/test/test_feature_pct_buy_trades.s

# target to generate assembly for a file
src/cppsrc/test/test_feature_pct_buy_trades.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_pct_buy_trades.cpp.s
.PHONY : src/cppsrc/test/test_feature_pct_buy_trades.cpp.s

src/cppsrc/test/test_feature_pct_sell_trades.o: src/cppsrc/test/test_feature_pct_sell_trades.cpp.o
.PHONY : src/cppsrc/test/test_feature_pct_sell_trades.o

# target to build an object file
src/cppsrc/test/test_feature_pct_sell_trades.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_pct_sell_trades.cpp.o
.PHONY : src/cppsrc/test/test_feature_pct_sell_trades.cpp.o

src/cppsrc/test/test_feature_pct_sell_trades.i: src/cppsrc/test/test_feature_pct_sell_trades.cpp.i
.PHONY : src/cppsrc/test/test_feature_pct_sell_trades.i

# target to preprocess a source file
src/cppsrc/test/test_feature_pct_sell_trades.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_pct_sell_trades.cpp.i
.PHONY : src/cppsrc/test/test_feature_pct_sell_trades.cpp.i

src/cppsrc/test/test_feature_pct_sell_trades.s: src/cppsrc/test/test_feature_pct_sell_trades.cpp.s
.PHONY : src/cppsrc/test/test_feature_pct_sell_trades.s

# target to generate assembly for a file
src/cppsrc/test/test_feature_pct_sell_trades.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_pct_sell_trades.cpp.s
.PHONY : src/cppsrc/test/test_feature_pct_sell_trades.cpp.s

src/cppsrc/test/test_feature_sum_5tick_volume.o: src/cppsrc/test/test_feature_sum_5tick_volume.cpp.o
.PHONY : src/cppsrc/test/test_feature_sum_5tick_volume.o

# target to build an object file
src/cppsrc/test/test_feature_sum_5tick_volume.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_sum_5tick_volume.cpp.o
.PHONY : src/cppsrc/test/test_feature_sum_5tick_volume.cpp.o

src/cppsrc/test/test_feature_sum_5tick_volume.i: src/cppsrc/test/test_feature_sum_5tick_volume.cpp.i
.PHONY : src/cppsrc/test/test_feature_sum_5tick_volume.i

# target to preprocess a source file
src/cppsrc/test/test_feature_sum_5tick_volume.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_sum_5tick_volume.cpp.i
.PHONY : src/cppsrc/test/test_feature_sum_5tick_volume.cpp.i

src/cppsrc/test/test_feature_sum_5tick_volume.s: src/cppsrc/test/test_feature_sum_5tick_volume.cpp.s
.PHONY : src/cppsrc/test/test_feature_sum_5tick_volume.s

# target to generate assembly for a file
src/cppsrc/test/test_feature_sum_5tick_volume.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intern_tests.dir/build.make CMakeFiles/intern_tests.dir/src/cppsrc/test/test_feature_sum_5tick_volume.cpp.s
.PHONY : src/cppsrc/test/test_feature_sum_5tick_volume.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... intern"
	@echo "... intern_project"
	@echo "... intern_tests"
	@echo "... src/cppsrc/main.o"
	@echo "... src/cppsrc/main.i"
	@echo "... src/cppsrc/main.s"
	@echo "... src/cppsrc/test/test_basic.o"
	@echo "... src/cppsrc/test/test_basic.i"
	@echo "... src/cppsrc/test/test_basic.s"
	@echo "... src/cppsrc/test/test_feature_n_trades.o"
	@echo "... src/cppsrc/test/test_feature_n_trades.i"
	@echo "... src/cppsrc/test/test_feature_n_trades.s"
	@echo "... src/cppsrc/test/test_feature_pct_buy_trades.o"
	@echo "... src/cppsrc/test/test_feature_pct_buy_trades.i"
	@echo "... src/cppsrc/test/test_feature_pct_buy_trades.s"
	@echo "... src/cppsrc/test/test_feature_pct_sell_trades.o"
	@echo "... src/cppsrc/test/test_feature_pct_sell_trades.i"
	@echo "... src/cppsrc/test/test_feature_pct_sell_trades.s"
	@echo "... src/cppsrc/test/test_feature_sum_5tick_volume.o"
	@echo "... src/cppsrc/test/test_feature_sum_5tick_volume.i"
	@echo "... src/cppsrc/test/test_feature_sum_5tick_volume.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

