name: Clang C++

on:
  push:
    branches: [ "ahuang9999-actions" ]
  pull_request:
    branches: [ "ahuang9999-actions" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: conan
      run: pipx install conan
    - name: INSTALL
      run: conan install clang-tidy
    - name: INSTALL2
      run: conan install clang-format
    - name: run1
      run: clang-tidy
    - name: run2
      run: clang-format
