name: Clang C++

on:
  push:
    branches: [ "ahuang9999-actions" ]
  pull_request:

jobs:
  format:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    
    - name: Install
      run: |
        python3 -m pip install --user pipx
        sudo apt update
        pipx install conan
        pipx install poetry
        sudo apt install clang-tidy
        sudo apt install clang-format

    - run: conan profile detect
        
    - name: build
      run: make build

    #- name: tidy
    #  run: find src/cppsrc/ -name '*.cpp' | xargs clang-tidy

    #- name: format
    #  run: find src/cppsrc/ -name '*.cpp' | xargs clang-format

    - name: run
      run: make format
