name: Clang C++

on:
  push:
    branches: [ "ahuang9999-actions" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    
    - name: Install
      run: |
        sudo apt update
        sudo apt install clang-tidy
        sudo apt install clang-format

    - name: tidy
      run: find src/cppsrc/ -name '*.cpp' | xargs clang-tidy

    - name: format
      run: find src/cppsrc/ -name '*.cpp' | xargs clang-format
