# This is a basic workflow that is manually triggered

name: Mypy and ruff

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      ahuang9999-actions
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with: 
        python-version: '3.12'
    
    - name: Install
      run: |
        make install_dependencies
        sudo apt install ninja-build
        poetry add requests
        poetry add pytest-mock
        poetry add scikit-learn
        
    - name: Install packages
      run: make install

    - name: pylint
      run: make pylint
      
      
    
