# This is a basic workflow that is manually triggered

name: Mypy and ruff

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      ahuang9999-actions
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          export PATH=$PATH:~/.local/bin
      
      
      - name: Install
        run: pipx install ruff
      - name: ruff
        run: ruff check

      - name: Install2
        run: pipx install mypy
      - name: mypy
        run: mypy .
      
      
    
